# This workflow will build the docs using latexmk

name: Compile with latexmk

on:
  push:
    branches: [ master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

env:
  ARTIFACT_NAME: application
  ARTIFACT_DIR: build

jobs:
  compile:
    # Don't run on forked repos.
    if: contains(fromJson('["wenh06"]'), github.repository_owner)

    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v4
    - name: Clear unnecessary system components
      run: |
        echo "Free space before cleanup:"
        df -h
        sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/share/boost
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        echo "Free space after cleanup:"
        df -h
    - name: Install system libraries
      run: |
        sudo apt update
        sudo apt install build-essential -y
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip' # caching pip dependencies
    - name: List existing Python packages
      run: |
        python -m pip list
    - name: Setup TeX Live
      # uses: teatimeguest/setup-texlive-action@v3
      uses: zauguin/install-texlive@v4
      with:
        # List of TeXLive-packages contained in the scheme-small
        # https://trac.macports.org/wiki/TeXLivePackages
        # tlmgr info --list scheme-small
        packages: >-
          scheme-small
          ctex
          cases
          pgf
          pgfplots
          tikz-cd
          hypdoc
          relsize
          xetex
          xecjk
          ifoddpage
          graphics
          graphics-cfg
          graphics-def
          etoolbox
          jknapltx
          mathtools
          anysize
          titlesec
          fancyhdr
          multirow
          float
          arydshln
          setspace
          boxedminipage
          hyperref
          imakeidx
          tocbibind
          listings
          xcolor
          shipunov
          caption
          booktabs
          enumitem
          metalogo
          xstring
          rsfs
          calrsfs
          psnfss
          newtx
          newtxsf
          newpx
          environ
          footmisc
          kvoptions
          iftex
          ltxcmds
          l3backend
          l3kernel
          l3packages
          courier
          pdfpages
          xpatch
          ntheorem
          biber
          biblatex
          biblatex-gb7714-2015
          diagbox
          pict2e
          xypic
          pstricks
          pstricks-add
          pst-tools
          pst-func
          pst-plot
          pst-text
          pst-node
          pst-math
          pst-3d
          pst-arrow
          pst-calculate
          makeplot
          numericplots
          dashbox
          zhnumber
          kvsetkeys
          xkeyval
          carlisle
          oberdiek
          eso-pic
          trimspaces
          hycolor
          bigfoot
          letltxmacro
          refcount
          auxhook
          url
          wasy
          wasy-type1
          wasysym
          rerunfilecheck
          multido
          siunitx
          translations
          mnsymbol
          pdflscape
          kastrup
          ulem
          pdftexcmds
          infwarerr
          kvdefinekeys
          pdfescape
          gettitlestring
          intcalc
          bigintcalc
          bitset
          stringenc
          uniquecounter
          babel
          babel-english
          gbt7714
          polyglossia
          csquotes
          currfile
          texcount
          cleveref
          lm
          soul
          circledsteps
          picture
          natbib
    - name: Install latexmk and extra software
      run: |
        perl -v
        sudo apt install latexmk -y
        sudo apt install texlive-pictures texlive-latex-extra texlive-fonts-recommended pdf2svg -y
        # sudo tlmgr install collection-fontsrecommended
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        sudo apt-get install ttf-mscorefonts-installer
    - name: Compile the document
      run: |
        python compile.py
        # assert there exists one pdf file in build folder
        ls build/*.pdf | wc -l | grep -q 1
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      # if is a tag, or manually triggered,
      # upload the pdf to the release
      if: startsWith(github.ref, 'refs/tags/')
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.ARTIFACT_DIR }}

  github-release:
    # github release and changelog
    needs: compile
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_DIR }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: |
            ${{ env.ARTIFACT_DIR }}/*.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
